/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = (CONFIG.defaultMode || "dark");

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#ff69b4");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.dark || {};
  root.style.setProperty("--bg", theme.background || "#1a1a2e");
  root.style.setProperty("--text", theme.text || "#ffffff");

  // Update toggle icon
  const btn = document.getElementById("theme-toggle");
  if (btn) btn.textContent = mode === "dark" ? "☀️" : "🌙";
}

function createThemeToggle() {
  const btn = document.createElement("button");
  btn.id = "theme-toggle";
  btn.title = "Toggle dark/light mode";
  btn.textContent = currentMode === "dark" ? "☀️" : "🌙";
  btn.addEventListener("click", () => {
    applyTheme(currentMode === "dark" ? "light" : "dark");
  });
  document.body.appendChild(btn);
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);
  createThemeToggle();

  // Set music source
  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    audio.querySelector("source").src = CONFIG.music;
    audio.load();
  }

  // Determine unique component types
  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  // Dynamically load component scripts
  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  // Render all sections
  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) {
      console.warn(`Component "${section.type}" not found, skipping.`);
      return;
    }
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

  // SweetAlert music prompt
  const isDark = currentMode === "dark";
  Swal.fire({
    title: "Play music in the background?",
    icon: "question",
    showCancelButton: true,
    confirmButtonColor: CONFIG.colors.accent || "#3085d6",
    cancelButtonColor: "#888",
    confirmButtonText: "Yes!",
    cancelButtonText: "No",
    background: isDark ? "#1e293b" : "#ffffff",
    color: isDark ? "#f1f5f9" : "#1e293b",
  }).then((result) => {
    if (result.isConfirmed && audio) {
      audio.play().catch(() => {});
    }
    buildTimeline(rendered);
  });
});

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(rendered) {
  const tl = gsap.timeline();

  tl.to(".container", {
    duration: 0.6,
    visibility: "visible"
  });

  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    // ── Tandai section ini sebagai "active" — HANYA untuk section non-overlay.
    // Overlay section (stars/fireworks/balloons/confetti/paperconfetti) sudah
    // punya pointer-events sendiri di CSS dan tidak boleh ikut mekanisme ini,
    // karena .section.active { pointer-events: auto } bisa override dan
    // menutupi klik ke section lain yang tampil bersamaan.
    if (!isOverlay) {
      tl.call(() => {
        el.classList.add("active");
      });
    }

    comp.animate(tl, el, CONFIG);

    if (comp.interactive && section.interactive !== false) {
      tl.call(() => {
        tl.pause();

        el._continue = () => {
          if (comp.exit) {
            const exitTl = gsap.timeline(); // timeline baru, mandiri, langsung play
            comp.exit(exitTl, el);
          }

          if (!isOverlay) {
            el.classList.remove("active");
          }

          tl.resume();
        };
      });
    } else {
      // Normal exit lifecycle
      if (comp.exit) {
        const next = rendered[i + 1];
        const nextIsOverlay = next && next.comp.overlay === true;

        if (nextIsOverlay) {
          deferredExits.push(() => {
            comp.exit(tl, el);
            if (!isOverlay) el.classList.remove("active");
          });
        } else if (!isOverlay) {
          comp.exit(tl, el);
          el.classList.remove("active");
        }
      } else if (!isOverlay) {
        // section tanpa exit() sendiri — tetap perlu dilepas activenya
        tl.call(() => {
          el.classList.remove("active");
        });
      }
    }
  });

  // Flush remaining exits
  deferredExits.forEach((fn) => fn());

  // Replay
  const replayBtn = document.getElementById("replay");

  if (replayBtn) {
    replayBtn.addEventListener("click", () => {
      // Reset semua active state sebelum restart
      document.querySelectorAll(".section.active").forEach((el) => {
        el.classList.remove("active");
      });
      tl.restart();
    });
  }
}